[workspace]
resolver = "2"
members = [
    "guessing_game",
    "methods",
    "reborrow",
    "rectangles",
    "slice",
    "Errors",
    "matchExample", 
    "traits", "lifetimes", "rsgrep", "closures", "smart_pointer", "threads", "message_passing", "mutex", "asynchronous_programming", "multithread_webserver",
]
